apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  pq-fabric.io/deployment-profile: staging
patches:
  - path: config-staging-patch.yaml
  - path: validator-production-patch.yaml
  - path: relay-disabled-patch.yaml
  - path: networkpolicy-production-patch.yaml
