apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secrets-aws.yaml
commonLabels:
  pq-fabric.io/deployment-profile: aws-staging
  pq-fabric.io/provider: aws
images:
  - name: pq-fabric
    newName: ghcr.io/keithwegner/pq-fabric
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
patches:
  - path: config-aws-staging-patch.yaml
  - path: validator-aws-staging-patch.yaml
  - path: relay-disabled-patch.yaml
  - path: networkpolicy-aws-staging-patch.yaml
