apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  pq-fabric.io/deployment-profile: three-region-simulation
  pq-fabric.io/region-model: nyc-london-singapore
