apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - validator-service.yaml
  - validator-statefulset.yaml
  - relay-service.yaml
  - relay-statefulset.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: pq-fabric
